'use client';
import dynamic from 'next/dynamic';
import { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowLeft, BookOpen, CalendarDays, CheckCircle2, Heart, Home, LockKeyhole, Pill, Sparkles } from 'lucide-react';
import type { CareItem, Checkin, Profile } from '@/lib/care-model';
import type { JourneyTask } from '@/lib/engagement-model';
import { pregnancyJourney, pregnancyWeek, journeyProgress, goalsFromRecords } from '@/lib/journey-engine';

const MamaWorldCanvas = dynamic(() => import('./mama-world-canvas').then((mod) => mod.MamaWorldCanvas), { ssr: false, loading: () => <div className="mama-world-loading">Entering your care space…</div> });
type Zone = 'hub' | 'clinic' | 'care' | 'learning' | 'journal' | 'journey' | 'mama';
export function ImmersiveMamaHome({ profile, checkins, tasks, appointments, onNavigate }: { profile: Profile; checkins: Checkin[]; tasks: JourneyTask[]; appointments: CareItem[]; onNavigate: (view: 'My care' | 'Learn' | 'My journal' | 'Journey' | 'Ask MAMA') => void }) {
  const [zone, setZone] = useState<Zone>('hub');
  const week = pregnancyWeek(profile); const goals = useMemo(() => goalsFromRecords(tasks, checkins.some((item) => item.date === new Date().toISOString().slice(0, 10)), appointments), [tasks, checkins, appointments]); const scores = journeyProgress(week, goals);
  const zoneAction = (next: Zone) => { setZone(next); if (next === 'clinic' || next === 'care') onNavigate('My care'); if (next === 'learning') onNavigate('Learn'); if (next === 'journal') onNavigate('My journal'); if (next === 'journey') onNavigate('Journey'); if (next === 'mama') onNavigate('Ask MAMA'); };
  const zoneOptions = [['clinic','Clinic',CalendarDays],['care','Care shelf',Pill],['learning','Learning',BookOpen],['journal','Journal',Heart],['journey','Journey mirror',Sparkles],['mama','Mama',Heart]] as const;
  return <main className="mama-world" aria-label="My Mama Home immersive care space"><div className="mama-world-scene"><MamaWorldCanvas activeZone={zone} onSelect={(value) => zoneAction(value as Zone)} progress={scores.journeyProgress} /></div><div className="mama-world-ui"><header><div><span className="mama-world-kicker"><Sparkles size={14} /> My Mama Home</span><h1>{week ? `Week ${week}, held with care.` : 'A warm space for your journey.'}</h1><p>Your private care space, with the next helpful thing close by.</p></div><button type="button" onClick={() => onNavigate('Journey')} aria-label="Open journey map"><Home size={18} /></button></header><nav className="mama-world-zones" aria-label="Care space zones">{zoneOptions.map(([id,label,Icon]) => <button type="button" key={id} className={zone === id ? 'active' : ''} onClick={() => zoneAction(id)}><Icon size={16} /><span>{label}</span></button>)}</nav><AnimatePresence mode="wait"><motion.section key={zone} className="mama-world-focus" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .22 }}>{zone === 'hub' ? <><span>YOUR NEXT MOMENT</span><h2>Choose a corner to begin.</h2><p>The space responds to what you have recorded and what you choose to prepare.</p></> : <ZoneCopy zone={zone as Exclude<Zone, 'hub'>} goals={goals.length} week={week} onOpen={() => zoneAction(zone)} />}</motion.section></AnimatePresence><div className="mama-world-status" aria-label="Journey status"><span><CheckCircle2 size={15} /> {scores.journeyProgress}% journey progress</span><span><LockKeyhole size={14} /> Private by default</span></div></div></main>;
}
function ZoneCopy({ zone, goals, week, onOpen }: { zone: Exclude<Zone, 'hub'>; goals: number; week: number | null; onOpen: () => void }) { const copy: Record<Exclude<Zone, 'hub'>, [string,string,string]> = { clinic: ['Clinic door','Appointments and care conversations','Keep the next question ready for your care team.'], care: ['Care shelf','Your medication and care goals','A quiet view of the practical things you chose to track.'], learning: ['Learning corner','One useful idea at a time','Clinician-reviewed lessons and scenarios will live here.'], journal: ['Journal','Notice how today feels','Your wellbeing check-in stays in your private care space.'], journey: ['Journey mirror',`Week ${week ?? '—'} of pregnancy`,`${goals} configured care goals are available for this stage.`], mama: ['Mama companion','A thoughtful prompt when it helps','Mama can help organise questions and next steps.'] }; const [title,heading,body]=copy[zone]; return <><span>{title}</span><h2>{heading}</h2><p>{body}</p><button type="button" onClick={onOpen}>Open {title.toLowerCase()} <ArrowLeft size={15} /></button></>; }
