'use client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, Float, Html, OrbitControls } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';

export function MamaWorldCanvas({ activeZone, onSelect, progress }: { activeZone: string; onSelect: (zone: any) => void; progress: number }) { return <Canvas camera={{ position: [0, 2.2, 8], fov: 42 }} dpr={[1, 1.5]} fallback={<div className="mama-world-fallback">Your care space is ready. Use the accessible zone controls below.</div>}><color attach="background" args={['#f7f2f4']} /><ambientLight intensity={1.4} /><directionalLight position={[3, 5, 4]} intensity={2} color="#ffd9ea" /><Environment preset="studio" /><Room activeZone={activeZone} onSelect={onSelect} progress={progress} /><OrbitControls enablePan={false} enableZoom={false} minPolarAngle={Math.PI / 2.6} maxPolarAngle={Math.PI / 2.05} /></Canvas>; }
function Room({ activeZone, onSelect, progress }: { activeZone: string; onSelect: (zone: any) => void; progress: number }) { return <group position={[0, -.45, 0]}><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[15,15]} /><meshStandardMaterial color="#f0e2e7" roughness={1} /></mesh><mesh position={[0,2,-2.5]}><planeGeometry args={[11,5]} /><meshStandardMaterial color="#fffafc" roughness={.9} /></mesh><ZoneMesh position={[-3,1,0]} color="#bc6d93" label="Clinic" zone="clinic" active={activeZone==='clinic'} onSelect={onSelect} /><ZoneMesh position={[-1,1,-.5]} color="#d69b83" label="Care" zone="care" active={activeZone==='care'} onSelect={onSelect} /><ZoneMesh position={[1,1,-.5]} color="#8067c4" label="Learn" zone="learning" active={activeZone==='learning'} onSelect={onSelect} /><ZoneMesh position={[3,1,0]} color="#e2a9bd" label="Journal" zone="journal" active={activeZone==='journal'} onSelect={onSelect} /><Float speed={1.4} rotationIntensity={.1} floatIntensity={.3}><ZoneMesh position={[0,2.5,-1]} color="#6b52c7" label={`Journey ${progress}%`} zone="journey" active={activeZone==='journey'} onSelect={onSelect} /></Float><Float speed={1.8} floatIntensity={.5}><mesh position={[0,1.1,1]} onClick={() => onSelect('mama')}><sphereGeometry args={[.55,24,24]} /><meshStandardMaterial color="#f45b93" roughness={.35} /></mesh><Html position={[0,1.8,1]} center><span className="mama-world-label">Mama</span></Html></Float></group>; }
function ZoneMesh({ position, color, label, zone, active, onSelect }: { position: [number,number,number]; color: string; label: string; zone: string; active: boolean; onSelect: (zone: any) => void }) { const ref = useRef<THREE.Mesh>(null); useFrame((_, delta) => { if (ref.current) ref.current.rotation.y += delta * (active ? .35 : .08); }); return <group position={position} onClick={() => onSelect(zone)}><mesh ref={ref} scale={active ? 1.18 : 1}><boxGeometry args={[1.5,1.7,.35]} /><meshStandardMaterial color={color} roughness={.38} metalness={.08} /></mesh><Html position={[0,-1.2,0]} center><span className="mama-world-label">{label}</span></Html></group>; }
