'use client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Html, OrbitControls } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';

export function MamaWorldCanvas({ activeZone, onSelect, progress }: { activeZone: string; onSelect: (zone: string) => void; progress: number }) {
  return <Canvas camera={{ position: [0, 2, 8], fov: 40 }} dpr={[1, 1.5]} fallback={<div className="mama-world-fallback">Your care space is ready. Use the accessible zone controls below.</div>}><color attach="background" args={['#24151e']} /><fog attach="fog" args={['#24151e', 7, 17]} /><ambientLight intensity={.6} color="#f5c1d2" /><pointLight position={[0, 4, 2]} intensity={2.5} color="#ffc2bc" /><pointLight position={[-4, 2, -1]} intensity={3} color="#a96bff" /><pointLight position={[4, 2, -1]} intensity={2.8} color="#ff9f73" /><Room activeZone={activeZone} onSelect={onSelect} progress={progress} /><OrbitControls enablePan={false} enableZoom={false} minPolarAngle={Math.PI / 2.55} maxPolarAngle={Math.PI / 2.08} /></Canvas>;
}
function Room({ activeZone, onSelect, progress }: { activeZone: string; onSelect: (zone: string) => void; progress: number }) { return <group position={[0, -.65, 0]}><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[15,15]} /><meshStandardMaterial color="#3e2532" /></mesh><mesh position={[0,2.8,-3.4]}><planeGeometry args={[12,6]} /><meshStandardMaterial color="#321e2a" /></mesh><mesh position={[0,2.5,-3.25]}><planeGeometry args={[3.1,3.2]} /><meshStandardMaterial color="#b96f82" emissive="#6b315f" emissiveIntensity={.7} /></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,.02,.3]}><circleGeometry args={[2.5,48]} /><meshStandardMaterial color="#6d3c55" /></mesh><Furniture /><Avatar /><Hotspot position={[-3.4,1.8,-2.4]} color="#ffb0cf" label="Clinic" zone="clinic" active={activeZone==='clinic'} onSelect={onSelect} /><Hotspot position={[-1.9,1.6,-2.5]} color="#ffb77d" label="Care shelf" zone="care" active={activeZone==='care'} onSelect={onSelect} /><Hotspot position={[2.8,1.35,-2.3]} color="#c8a2ff" label="Journal" zone="journal" active={activeZone==='journal'} onSelect={onSelect} /><Hotspot position={[1.55,2.55,-2.4]} color="#e79ac6" label={`Journey ${progress}%`} zone="journey" active={activeZone==='journey'} onSelect={onSelect} /><Hotspot position={[-.2,1.1,.35]} color="#ff81b1" label="Mama" zone="mama" active={activeZone==='mama'} onSelect={onSelect} /></group>; }
function Furniture() { return <group><mesh position={[-3.7,1.55,-2.9]}><boxGeometry args={[1.7,2.8,.45]} /><meshStandardMaterial color="#5a2e3e" /></mesh><mesh position={[3.25,.7,-2.65]}><boxGeometry args={[2.5,.12,.9]} /><meshStandardMaterial color="#4a2632" /></mesh><mesh position={[-4.1,.75,-.9]}><boxGeometry args={[2.2,1.05,.9]} /><meshStandardMaterial color="#71465b" /></mesh><mesh position={[0,1.1,.1]}><sphereGeometry args={[.35,20,20]} /><meshStandardMaterial color="#f7d8c4" emissive="#ff9a6d" emissiveIntensity={1.5} /></mesh></group>; }
function Avatar() { const ref = useRef<THREE.Group>(null); useFrame((state) => { if (ref.current) ref.current.position.y = .1 + Math.sin(state.clock.elapsedTime*.7)*.025; }); return <group ref={ref} position={[0,.1,.45]}><mesh position={[0,1.75,0]}><sphereGeometry args={[.42,24,24]} /><meshStandardMaterial color="#9a5e50" /></mesh><mesh position={[0,1.1,0]}><capsuleGeometry args={[.58,.9,8,16]} /><meshStandardMaterial color="#b87586" /></mesh><mesh position={[0,.85,.52]} scale={[.75,.72,.55]}><sphereGeometry args={[.65,24,24]} /><meshStandardMaterial color="#e49a9b" /></mesh><Html position={[0,2.45,0]} center><span className="mama-world-avatar-label">Your care space</span></Html></group>; }
function Hotspot({ position, color, label, zone, active, onSelect }: { position: [number,number,number]; color: string; label: string; zone: string; active: boolean; onSelect: (zone: string) => void }) { const ref = useRef<THREE.Mesh>(null); useFrame((_, delta) => { if (ref.current) { ref.current.rotation.y += delta*(active?.45:.12); const scale=active?1.25:1; ref.current.scale.lerp(new THREE.Vector3(scale,scale,scale),.12); } }); return <group position={position} onClick={() => onSelect(zone)}><mesh ref={ref}><sphereGeometry args={[.18,20,20]} /><meshStandardMaterial color={color} emissive={color} emissiveIntensity={active?2.8:1.2} /></mesh><pointLight color={color} intensity={active?1.4:.5} distance={1.4} /><Html position={[0,-.42,0]} center><span className="mama-world-label">{label}</span></Html></group>; }
