'use client';
import { useMemo, useState } from 'react';
import { Baby, Check, ChevronRight, CircleHelp, Lock, Sparkles } from 'lucide-react';
import type { CareItem, Checkin, Profile } from '@/lib/care-model';
import type { JourneyTask } from '@/lib/engagement-model';
import { goalsFromRecords, journeyProgress, pregnancyJourney, pregnancyWeek } from '@/lib/journey-engine';

export function PregnancyJourneyHome({ profile, checkins, tasks, appointments, onCare, onLearn, onMama }: { profile: Profile; checkins: Checkin[]; tasks: JourneyTask[]; appointments: CareItem[]; onCare: () => void; onLearn: () => void; onMama: () => void; }) {
  const [scenarioOpen, setScenarioOpen] = useState(false);
  const week = pregnancyWeek(profile);
  const goals = useMemo(() => goalsFromRecords(tasks, checkins.some((item) => item.date === new Date().toISOString().slice(0, 10)), appointments), [tasks, checkins, appointments]);
  const scores = journeyProgress(week, goals);
  const currentIndex = week == null ? 0 : pregnancyJourney.milestones.reduce((index, milestone, nextIndex) => milestone.week && milestone.week <= week ? nextIndex : index, 0);
  return <div className="pregnancy-journey-engine">
    <section className="pregnancy-engine-hero"><div><span className="journey-engine-kicker"><Baby size={16} /> Pregnancy journey</span><h2>{week == null ? 'Add your pregnancy dates to begin.' : `Week ${week} of your journey.`}</h2><p>Small, meaningful steps for care, learning and preparation. MAMA does not diagnose or replace your care team.</p></div><div className="pregnancy-week-orb"><strong>{week == null ? '—' : week}</strong><span>weeks</span></div></section>
    <section className="pregnancy-engine-score-grid" aria-label="Journey progress"><Score label="Journey progress" value={scores.journeyProgress} /><Score label="Care consistency" value={scores.careConsistency} /><Score label="Health knowledge" value={scores.healthKnowledge} /><Score label="Preparedness" value={scores.preparedness} /></section>
    <section className="pregnancy-engine-card"><div className="engine-section-heading"><div><span>Today</span><h3>Your care goals</h3></div><button type="button" onClick={onCare}>View care <ChevronRight size={16} /></button></div><div className="pregnancy-goal-list">{goals.map((goal) => <div className="pregnancy-goal" key={goal.id}><span className={'goal-status ' + goal.status}>{goal.status === 'completed' ? <Check size={15} /> : goal.required ? '!' : '·'}</span><div><b>{goal.title}</b><small>{goal.description}</small></div><em>{goal.status}</em></div>)}</div></section>
    <section className="pregnancy-engine-card pregnancy-engine-map"><div className="engine-section-heading"><div><span>Your path</span><h3>Pregnancy journey map</h3></div><Sparkles size={19} aria-hidden="true" /></div><ol>{pregnancyJourney.milestones.map((milestone, index) => <li className={index < currentIndex ? 'complete' : index === currentIndex ? 'current' : 'upcoming'} key={milestone.id}><span>{index < currentIndex ? <Check size={14} /> : index === currentIndex ? <Baby size={14} /> : <Lock size={13} />}</span><div><b>{milestone.title}</b><small>{milestone.description}</small></div></li>)}</ol></section>
    <div className="pregnancy-engine-two-up"><section className="pregnancy-engine-card"><span className="journey-engine-kicker"><Sparkles size={15} /> Learn at your pace</span><h3>One useful lesson for this stage</h3><p>Clinician-reviewed pregnancy learning will appear here as content is approved.</p><button type="button" className="engine-primary" onClick={onLearn}>Open learning <ChevronRight size={16} /></button></section><section className="pregnancy-engine-card"><span className="journey-engine-kicker"><CircleHelp size={15} /> Mama is with you</span><h3>Prepare for your next conversation</h3><p>Save a question or get help organising what you want to discuss.</p><button type="button" className="engine-secondary" onClick={onMama}>Ask MAMA <ChevronRight size={16} /></button></section></div>
    <section className="pregnancy-engine-card pregnancy-engine-scenario"><div><span className="journey-engine-kicker">Interactive education</span><h3>Know what needs prompt attention</h3><p>Use clinician-reviewed scenarios to practise preparing for care conversations.</p></div><button type="button" onClick={() => setScenarioOpen((open) => !open)}>{scenarioOpen ? 'Close scenario' : 'Try a scenario'} <ChevronRight size={16} /></button>{scenarioOpen && <output className="scenario-placeholder"><b>Scenario content awaiting clinical review.</b><p>The reusable scenario engine is ready, but no emergency thresholds or clinical answer have been invented here.</p></output>}</section>
  </div>;
}
function Score({ label, value }: { label: string; value: number }) { return <div className="pregnancy-engine-score"><span>{label}</span><strong>{value}%</strong><div><i style={{ width: `${value}%` }} /></div></div>; }
